<a href="https://colab.research.google.com/github/SeoyoungOhMe/skt-fly-ai-challenger-class/blob/master/01_numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#넘파이(Numpy) 튜토리얼

In [ ]:
import numpy as np

print(np.__version__) # 버전 확인

1.23.5


In [ ]:
import pandas as pd
import matplotlib
import seaborn as sns

print(pd.__version__)
print(matplotlib.__version__)
print(sns.__version__)

1.5.3
3.7.1
0.12.2


### 1.넘파이 배열

In [ ]:
# 파이썬 리스트
arr = [1, 2, 3, 4, 5]
type(arr)

list

In [ ]:
# 넘파이 배열 ndarray 객체로 되어있다

a = np.array(arr)
type(a)

print(a)
a

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [ ]:
# 배열의 각 요소에 1을 더해서 리스트

arr + [1]

[1, 2, 3, 4, 5, 1]

In [ ]:
print(a)
print(a+1)

[1 2 3 4 5]
[2 3 4 5 6]


In [ ]:
# 넘파이 배열은 각 요소가 모두 같은 데이터 타입을 가저야 한다

arr = [1, 'A', 3.14]
arr

[1, 'A', 3.14]

In [ ]:
arr = [1., 2., 3., 4., 5.]
a = np.array(arr)
a

array([1., 2., 3., 4., 5.])

In [ ]:
# 넘파이 배열이 가지고 있는 속성
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
float64


In [ ]:
# 튜플
print(a.shape)
print(type(a.shape))

(5,)
<class 'tuple'>


In [ ]:
b = [1, 2, 3]
c = (1, 2, 3)
type(b), type(c)

(list, tuple)

In [ ]:
type([1]), len([1])

(list, 1)

In [ ]:
b = [[1, 2, 3], [3, 4, 5]]
c = np.array(b)

In [ ]:
c.shape

(2, 3)

In [ ]:
print(c)

[[1 2 3]
 [3 4 5]]


In [ ]:
a = np.array([[[1, 2], [2, 3], [3, 4]], [[3, 4], [4, 5], [5, 6]]]) # 2개짜리가 3개 들어있는 게 총 2개 있다
a.shape

(2, 3, 2)

In [ ]:
print(a)

[[[1 2]
  [2 3]
  [3 4]]

 [[3 4]
  [4 5]
  [5 6]]]


In [ ]:
# (3, 1, 3) -> 3개짜리가 하나 들어있는 게 총 3개 있다
a = np.array([[[1, 2, 3]], [[4, 5, 6]], [[7, 8, 9]]])
a.shape

(3, 1, 3)

### 2.배열 생성 함수

#### arange() 함수

In [ ]:
arr = np.arange(12, 2, -1)
arr

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.arange(12).reshape(3, 4)

In [ ]:
a.shape

(3, 4)

In [ ]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.arange(12)
a.shape

(12,)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.reshape(3, 4)
a.shape

(12,)

In [ ]:
a = a.reshape(3, 2, 2)
a.shape

(3, 2, 2)

In [ ]:
a.reshape(-1, 3, 4).shape

(1, 3, 4)

In [ ]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

### 4.범용함수

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

![](https://th.bing.com/th/id/OIP.pFidENyALqe9EbUcvJIdGgHaD6?rs=1&pid=ImgDetMain)

In [ ]:
np.sum(a, axis=1) # 열 기준

array([ 6, 22, 38])

In [ ]:
np.sum(a, axis=0) # 행 기준

array([12, 15, 18, 21])

In [ ]:
np.mean(a)

5.5

In [ ]:
np.mean(a, axis=0)

array([4., 5., 6., 7.])

In [ ]:
np.mean(a, axis=1)

array([1.5, 5.5, 9.5])

In [ ]:
# argmax()

a = np.array([2, 3, 7, 4, 6])
np.argmax(a)

2

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 5.인덱싱(indexing), 슬라이싱(slicing)
- 인덱싱을 하면 차원이 줄어든다.
- 슬라이싱은 차원이 보존된다.



In [ ]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[3] # 인덱싱

3

In [ ]:
a[2: 5] # 슬라이싱

array([2, 3, 4])

In [ ]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[:-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[-5:]

array([ 7,  8,  9, 10, 11])

In [ ]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[0]

array([0, 1, 2, 3])

In [ ]:
a[1][1]

5

In [ ]:
a[1, 1]

5

In [ ]:
a[1, 2:]

array([6, 7])

In [ ]:
a[1:, 2:]

array([[ 6,  7],
       [10, 11]])

- Fancy Indexing

In [ ]:
a[[0, 2]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
a[[2, 0]]

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

- Boolean Indexing

In [ ]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
idx = [True, False, False, True, False]

In [ ]:
a[idx]

array([0, 3])

In [ ]:
a > 2

array([False, False, False,  True,  True])

In [ ]:
a[ a>2 ]

array([3, 4])

### 6.브로드캐스팅(Broad Casting)

In [ ]:
a = np.array([3, 4, 5])
a + np.array([1])

array([4, 5, 6])

In [ ]:
x = np.arange(6).reshape(3, 2)

In [ ]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
y = np.arange(6).reshape(2, 3)

In [ ]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
z = np.array([1, 2, 3])
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y+z

array([[1, 3, 5],
       [4, 6, 8]])

### 배열 합치기
- stack(axis 갯수가 증가함)
- concatenate (차원이 유지)

In [ ]:
X = np.array([[1, 1], [2, 2]])
X

array([[1, 1],
       [2, 2]])

In [ ]:
Y = np.array([[3, 3], [4, 4]])
Y

array([[3, 3],
       [4, 4]])

In [ ]:
np.concatenate((X, Y), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
X.shape, Y.shape

((2, 2), (2, 2))

In [ ]:
Z=np.concatenate((X, Y), axis=1)
Z

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
Z=np.stack((X, Y))
Z

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])