<a href="https://colab.research.google.com/github/SeoyoungOhMe/skt-fly-ai-challenger-class/blob/master/example_policy_eval_gridworld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Simple Gridworld Problem

In [ ]:
import numpy as np

P = np.array([
    # up
    # 0  1  2  3. 4. 5. 6. 7. 8. 9. 10.11
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # down
    # 0  1  2  3. 4. 5. 6. 7. 8. 9. 10.11
    [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]],

    # left
    # 0  1  2  3. 4. 5. 6. 7. 8. 9. 10.11
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

    # right
    # 0  1  2  3. 4. 5. 6. 7. 8. 9. 10.11
    [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],], dtype='float32')

P.shape

(4, 12, 12)

In [ ]:
P = P.transpose(1, 0, 2)

In [ ]:
P.shape

(12, 4, 12)

In [ ]:
R = np.array([
    # 0  1    2   3.  4.  5.  6.  7.  8.  9.  10. 11
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1], # up
    [ 1, -1, -1, -1,  1,  1,  1, -1, -1, -1,  1, -1], # down
    [-1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1], # left
    [-1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1]], #right
    dtype='float32')

In [ ]:
R.shape

(4, 12)

In [ ]:
R = R.transpose()

In [ ]:
R.shape

(12, 4)

In [ ]:
pi = np.ones((15, 4), dtype='float32') * 0.25

In [ ]:
pi.shape

(15, 4)

### In summary,

In [ ]:
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 12), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    print(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )))
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((12, 4), dtype='float32')
    pi[range(12), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((12, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

print(pi)

[[-1.7497171   0.2512421  -1.7497171  -1.7499228 ]
 [-1.7499228  -1.7499228   0.25028288 -1.7499228 ]
 [-1.7499228  -1.7499228   0.2500773  -1.7497171 ]
 [-1.7497171  -1.7497171   0.2500773  -1.7487578 ]
 [-1.7497171   0.2519244  -1.7487578  -1.7451689 ]
 [-1.7487578   0.25483102 -1.7480756  -1.7451689 ]
 [-1.7451689   0.27061975 -1.7480756  -1.7451689 ]
 [-1.7480756  -1.7451689  -1.7451689   0.27061975]
 [-1.7451689  -1.7293802  -1.7451689   0.35718274]
 [-1.6428173  -1.6428173  -1.7293802   0.7295659 ]
 [ 0.38079077  0.7295659  -1.6428173  -1.2704341 ]
 [ 0.38079077 -1.2704341  -1.6192093  -1.6192093 ]]
[[0.49999952 2.4999995  0.49999952 0.49999952]
 [0.49999952 0.49999952 2.4999995  0.49999952]
 [0.49999952 0.49999952 2.4999995  0.49999952]
 [0.49999952 0.49999952 2.4999995  0.49999952]
 [0.49999952 2.4999995  0.49999952 0.49999952]
 [0.49999952 2.4999995  0.49999952 0.49999952]
 [0.49999952 2.4999995  0.49999952 0.49999952]
 [0.49999952 0.49999952 0.49999952 2.4999995 ]
 [0.4999995